FROM python:3.9

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY producer.py /app
COPY database_creation.py /app
COPY models.py /app

CMD ["python", "producer.py"]
